[target.aarch64-linux-android]
ar = "$NDK_TOOLCHAIN/arm64/bin/aarch64-linux-android-ar"
linker = "$NDK_TOOLCHAIN/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "$NDK_TOOLCHAIN/arm/bin/arm-linux-androideabi-ar"
linker = "$NDK_TOOLCHAIN/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "$NDK_TOOLCHAIN/x86/bin/i686-linux-android-ar"
linker = "$NDK_TOOLCHAIN/x86/bin/i686-linux-android-clang"
