[package]
name = "v8_macros"
version = "0.1.0"
authors = ["Hoang Phan <pquochoang2007@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.12"
v8 = { path = "../v8" }

[dependencies.syn]
version = "0.15.32"
features = ["full", "extra-traits"]
