[package]
name = "rust"
version = "0.1.0"
authors = ["Hoang Phan <pquochoang2007@gmail.com>"]

[lib]
name = "rust"
crate-type = ["staticlib"]

rustc-link-search = ["./lib"]
rustc-link-lib = ["curl"]

[target.'cfg(target_os="android")'.dependencies]
num-complex = "0.2"
itertools = "*"
libc = "0.2"
num = "0.2.0"
jni = { version = "0.10.2", default-features = false }
curl = "0.4.17"

[dependencies]
num-complex = "0.2"
libc = "0.2"
num = "0.2.0"

[[example]]
name = "main"
path = "examples/main.rs"
