[package]
name = "rust"
version = "0.1.0"
authors = ["Hoang Phan <pquochoang2007@gmail.com>"]

[lib]
name = "rust"
crate-type = ["staticlib"]

[target.'cfg(target_os="android")'.dependencies]
ws = "0.7.9"
libc = "0.2"
serde = "1.0.60"
serde_json = "1.0"
serde_derive = "1.0"
num-complex = "0.2"
image = "0.20.0"
imageproc = "0.16.0"
itertools = "*"
jni = { version = "0.10.2", default-features = false }

[dependencies]
image = "*"
num-complex = "0.2"
libc = "0.2"

[[example]]
name = "main"
path = "examples/main.rs"
