[package]
name = "rust"
version = "0.1.0"
authors = ["Hoang Phan <pquochoang2007@gmail.com>"]

[lib]
name = "rust"
crate-type = ["staticlib"]

[target.'cfg(target_os="android")'.dependencies.jni]
git = "https://github.com/hoangpq/jni-rs"
branch = "feat/detach_current_thread"
version = "*"
default-features = false

[target.'cfg(target_os="android")'.dependencies]
num-complex = "0.2"
itertools = "*"
libc = "0.2"
num = "0.2.0"

[dependencies]
num-complex = "0.2"
libc = "0.2"
num = "0.2.0"

[[example]]
name = "main"
path = "examples/main.rs"
